// Custom images for skill planet
const customImages = [
  { src: "/skills/c.png", alt: "C" },
  { src: "/skills/cpp.svg", alt: "C++" },
  { src: "/skills/java.svg", alt: "Java" },
  { src: "/skills/py.svg", alt: "Python" },
  { src: "/skills/html5.png", alt: "HTML5" },
  { src: "/skills/css.png", alt: "CSS3" },
  { src: "/skills/bootstrap.png", alt: "Bootstrap" },
  { src: "/skills/js.png", alt: "JavaScript" },
  { src: "/skills/ts.png", alt: "TypeScript" },
  { src: "/skills/react.png", alt: "React" },
  { src: "/skills/redux.svg", alt: "Redux" },
  { src: "/skills/tailwind.svg", alt: "Tailwind CSS" },
  { src: "/skills/nodejs.png", alt: "Node.js" },
  { src: "/skills/express.png", alt: "Express" },
  { src: "/skills/postman.png", alt: "Postman" },
  { src: "/skills/mongodb.png", alt: "MongoDB" },
  { src: "/skills/postgresql.png", alt: "PostgreSQL" },
  { src: "/skills/nextjs.png", alt: "Next.js" },
  { src: "/skills/prisma.png", alt: "Prisma" },
  { src: "/skills/csharp.png", alt: "C#" },
  { src: "/skills/dotnet.svg", alt: ".NET" },
  { src: "/skills/sqlserver.png", alt: "SQL Server" },
  { src: "/skills/blazor.png", alt: "Blazor" },
  { src: "/skills/aws.png", alt: "AWS" },
  { src: "/skills/gcp.svg", alt: "Google Cloud" },
  { src: "/skills/git.svg", alt: "Git" },
  { src: "/skills/github.png", alt: "GitHub" },
];

export { customImages };