const projects = [
  {
    id: "pankh",
    name: "PANKH",
    tagline: "Official Full Stack Event & Club Management Portal",
    thumbnail: "/pankh1.png",
    description: "A 3D visualization app to explore galaxies and star systems.",
    techStack: [
      "Next.js",
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Cloudinary",
    ],
    images: [
      "/pankh1.png",
      "/pankh2.png",
      "/pankh3.png",
      "/pankh4.png",
      "/pankh5.png",
    ],
    github: "https://github.com/hemaxpatel/PANKH",
  },
  {
    id: "engineers-depot",
    name: "Engineer's Depot",
    tagline: "Full Stack Job Portal",
    thumbnail: "/engineers-depot1.png",
    description: "A 3D visualization app to explore galaxies and star systems.",
    techStack: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Cloudinary",
    ],
    images: [
      "/engineers-depot1.png",
      "/engineers-depot2.jpg",
      "/engineers-depot3.png",
    ],
    github: "https://github.com/hemaxpatel/Engineers-Depot",
  },
  {
    id: "urban-axis",
    name: "Urban Axis",
    tagline: "Full Stack Real Estate Web App",
    thumbnail: "/urban-axis1.png",
    description: "A 3D visualization app to explore galaxies and star systems.",
    techStack: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Prisma",
      "Socket.io",
      "Cloudinary",
    ],
    images: [
      "/urban-axis1.png",
      "/urban-axis2.png",
      "/urban-axis3.png",
      "/urban-axis4.png",
      "/urban-axis5.png",
    ],
    github: "https://github.com/hemaxpatel/Urban-Axis",
  },
  {
    id: "digital-rosca",
    name: "Digital ROSCA",
    tagline: "Full Stack ROSCA FinTech Web App",
    thumbnail: "/digital-rosca1.png",
    description: "A 3D visualization app to explore galaxies and star systems.",
    techStack: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Cloudinary",
      "Razorpay",
    ],
    images: [
      "/digital-rosca1.png",
      "/digital-rosca2.png",
      "/digital-rosca3.png",
      "/digital-rosca4.png",
    ],
    github: "https://github.com/hemaxpatel/Digital-ROSCA",
  },
  {
    id: "sabras-mukhwas",
    name: "Sabras Mukhwas",
    tagline: "Full Stack Subras Mukhwas Online Store",
    thumbnail: "/sabras-mukhwas1.jpg",
    description: "A 3D visualization app to explore galaxies and star systems.",
    techStack: ["React.js", "Node.js", "Express.js", "MongoDB", "Stripe"],
    images: [
      "/sabras-mukhwas1.jpg",
      "/sabras-mukhwas2.jpg",
      "/sabras-mukhwas3.jpg",
      "/sabras-mukhwas4.jpg",
      "/sabras-mukhwas5.jpg",
    ],
    github: "https://github.com/hemaxpatel/Sabras-Mukhwas",
  },
  {
    id: "om-party-plot",
    name: "Om Partyplot",
    tagline: "Live OM Party Plot Website",
    thumbnail: "/om-party-plot1.png",
    description: "A 3D visualization app to explore galaxies and star systems.",
    techStack: ["HTML", "CSS", "JavaScript"],
    images: [
      "/om-party-plot1.png",
      "/om-party-plot2.png",
      "/om-party-plot3.png",
    ],
    github: "https://github.com/hemaxpatel/om-party-plot",
  },
  {
    id: "ai-world",
    name: "AI World",
    tagline: "AI tools Finding Website",
    thumbnail: "/ai-world1.png",
    description: "A 3D visualization app to explore galaxies and star systems.",
    techStack: ["HTML", "CSS", "JavaScript"],
    images: [
      "/ai-world1.png",
      "/ai-world2.png",
      "/ai-world3.png",
      "/ai-world4.png",
      "/ai-world5.png",
    ],
    github: "https://github.com/hemaxpatel/AI-World",
  },
];

export default projects;
