const projects = [
  {
    id: "pankh",
    name: "PANKH",
    tagline: "Official Full Stack Event & Club Management Portal",
    thumbnail: "/projects/pankh1.png",
    description:
      "A live Web Application currently being used by 1000+ students and faculty members. PANKH is an innovative Event & Club Management platform designed to modernize how events and clubs are managed at our college. The platform replaces traditional offline paperwork with a streamlined digital system, making event organization, participation and monitoring attendance more efficient than ever. Built by students, for students – PANKH is a step towards a smarter and more connected campus!",
    techStack: [
      "Next.js",
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Cloudinary",
    ],
    images: [
      "/projects/pankh1.png",
      "/projects/pankh2.png",
      "/projects/pankh3.png",
      "/projects/pankh4.png",
      "/projects/pankh5.png",
    ],
    github: "https://github.com/hemaxpatel/PANKH",
  },
  {
    id: "Edu-Dash",
    name: "Edu Dash",
    tagline: "Full Stack School Management System",
    thumbnail: "/projects/edu-dash1.jpg",
    description:
      "Edu Dash is a full-stack school management system designed to streamline administrative tasks and enhance communication within educational institutions. It offers a comprehensive suite of features for managing student information, attendance, grades, and staff details, all accessible through an intuitive web interface. Edu Dash aims to simplify school management processes, improve efficiency, and foster better engagement among students, parents, teachers, and administrators.",
    techStack: [
      "Next.js",
      "TypeScript",
      "PostgreSQL",
      "Prisma ORM",
      "Tailwind CSS",
      "Cloudinary",
      "Clerk Auth",
    ],
    images: [
      "/projects/edu-dash1.jpg",
      "/projects/edu-dash2.jpg",
      "/projects/edu-dash3.jpg",
      "/projects/edu-dash4.jpg",
      "/projects/edu-dash5.jpg",
      "/projects/edu-dash6.jpg",
      "/projects/edu-dash7.jpg",
      "/projects/edu-dash8.jpg",
    ],
    github: "https://github.com/hemaxpatel/Edu-Dash",
  },
  {
    id: "digital-rosca",
    name: "Digital ROSCA",
    tagline: "Full Stack ROSCA FinTech Web App",
    thumbnail: "/projects/digital-rosca1.png",
    description:
      "Digital ROSCA is a web application designed to digitize and streamline the traditional Rotating Savings and Credit Association (ROSCA) system. It enables groups of users to collectively save money and provide credit in a transparent, secure, and automated manner.",
    techStack: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Cloudinary",
      "Razorpay",
    ],
    images: [
      "/projects/digital-rosca1.png",
      "/projects/digital-rosca2.png",
      "/projects/digital-rosca3.png",
      "/projects/digital-rosca4.png",
    ],
    github: "https://github.com/hemaxpatel/Digital-ROSCA",
  },
  {
    id: "urban-axis",
    name: "Urban Axis",
    tagline: "Full Stack Real Estate Web App",
    thumbnail: "/projects/urban-axis1.png",
    description:
      "Urban Axis is a modern real estate platform designed to streamline the process of buying, selling, and renting properties. It provides an intuitive interface for users to explore property listings, connect with sellers, and engage in real-time conversations with agents. Built to simplify real estate transactions – Urban Axis is the future of property buying and selling!",
    techStack: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Prisma ORM",
      "Socket.io",
      "Cloudinary",
    ],
    images: [
      "/projects/urban-axis1.png",
      "/projects/urban-axis2.png",
      "/projects/urban-axis3.png",
      "/projects/urban-axis4.png",
      "/projects/urban-axis5.png",
    ],
    github: "https://github.com/hemaxpatel/Urban-Axis",
  },
  {
    id: "sabras",
    name: "Sabras",
    tagline: "Full Stack Subras Online Store",
    thumbnail: "/projects/sabras1.jpg",
    description:
      "Sabras is a powerful and scalable full-stack e-commerce web application that provides a seamless online shopping experience for users and robust management tools for administrators. Designed with a focus on performance, usability, and security, Sabras demonstrates the core functionalities required to run a modern online store. Sabras enables customers to browse products, manage their cart, and complete secure purchases, while also offering administrators a dedicated dashboard to manage products, view orders, and oversee user activity. The application integrates real-time payment functionality and leverages modern technologies to create an efficient and user-friendly shopping experience.",
    techStack: ["React.js", "Node.js", "Express.js", "MongoDB", "Stripe"],
    images: [
      "/projects/sabras1.jpg",
      "/projects/sabras2.jpg",
      "/projects/sabras3.jpg",
      "/projects/sabras4.jpg",
      "/projects/sabras5.jpg",
    ],
    github: "https://github.com/hemaxpatel/Sabras",
  },
  {
    id: "engineers-depot",
    name: "Engineer's Depot",
    tagline: "Full Stack Job Portal",
    thumbnail: "/projects/engineers-depot1.png",
    description:
      "Engineer’s Depot is a full-stack MERN job portal that connects job seekers with recruiters. It simplifies the job search process by providing an intuitive platform to browse job listings, apply for positions, and communicate with recruiters in real-time. Empowering job seekers and recruiters – Engineer’s Depot is the future of job search and hiring!",
    techStack: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Cloudinary",
    ],
    images: [
      "/projects/engineers-depot1.png",
      "/projects/engineers-depot2.jpg",
      "/projects/engineers-depot3.png",
    ],
    github: "https://github.com/hemaxpatel/Engineers-Depot",
  },
  {
    id: "velocity",
    name: "Velocity",
    tagline: "Full Stack Project Management Tool",
    thumbnail: "/projects/velocity1.jpg",
    description:
      "Velocity is a comprehensive project management tool designed to enhance team collaboration and streamline project workflows. It provides a user-friendly interface for managing tasks, tracking progress, and facilitating communication among team members. With features like task assignment, deadline tracking, and real-time updates, Velocity empowers teams to work more efficiently and effectively.",
    techStack: [
      "Next.js",
      "Node.js",
      "Express.js",
      "PostgreSQL",
      "Prisma ORM",
      "Redux Toolkit",
      "Tailwind CSS",
      "AWS (S3, EC2, RDS, Cognito, Lambda, Amplify, Api Gateway)",
    ],
    images: [
      "/projects/velocity1.jpg",
      "/projects/velocity2.jpg",
      "/projects/velocity3.jpg",
      "/projects/velocity4.jpg",
      "/projects/velocity5.jpg",
      "/projects/velocity6.jpg",
    ],
    github: "https://github.com/hemaxpatel/Velocity",
  },

  // {
  //   id: "om-party-plot",
  //   name: "Om Partyplot",
  //   tagline: "Live OM Party Plot Website",
  //   thumbnail: "/projects/om-party-plot1.png",
  //   description:
  //     "OM Party Plot is a sleek and responsive portfolio website created for showcasing the offerings and facilities of a party plot venue. It is designed to provide visitors with all the essential information about the venue, including available services, event types, gallery images, pricing, and contact details, making it easy for potential clients to explore and book the venue.",
  //   techStack: ["HTML", "CSS", "JavaScript"],
  //   images: [
  //     "/projects/om-party-plot1.png",
  //     "/projects/om-party-plot2.png",
  //     "/projects/om-party-plot3.png",
  //   ],
  //   github: "https://github.com/hemaxpatel/om-party-plot",
  // },
  {
    id: "ai-world",
    name: "AI World",
    tagline: "AI tools Finding Website",
    thumbnail: "/projects/ai-world1.png",
    description:
      "AI World is a modern and user-friendly website designed to help users search, explore, and discover a wide range of AI tools based on their needs and categories. Built to simplify the growing world of artificial intelligence, this platform serves as a centralized hub where users can filter tools by category, search by name, and instantly access detailed information and links to each tool. Whether you're a developer, marketer, designer, or just curious about AI, this website makes it easy to find the right tool for your use case.",
    techStack: ["HTML", "CSS", "JavaScript"],
    images: [
      "/projects/ai-world1.png",
      "/projects/ai-world2.png",
      "/projects/ai-world3.png",
      "/projects/ai-world4.png",
      "/projects/ai-world5.png",
    ],
    github: "https://github.com/hemaxpatel/AI-World",
  },
];

export default projects;
